lib_dir = "/opt/libs/"
bin_dir = "/opt/binaries/"
trace_dir = "./themis/data/"
trusted_graph_dir = "./themis/graphs/trusted/"
dirty_graph_dir = "./themis/graphs/dirty/"
result_dir = "./themis/results/"
img_dir = "./themis/graphs/img/"
sample_dir = "./themis/samples/"
traced_libcalls_file = "./themis/trace_conf/libc_i_o.txt"
args = [
    "ptolemy@172.16.0.10",
    "sleep 5 & uname -a & sleep 5 & uname -a"
]
